### ISSUE TITLE
IonToExcel gives an error

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-serdes#117]
### Expected Behavior

IonToExcel task should work as expected.

### Actual Behaviour

IonToExcel task gives as error.
The error is:
```
2024-06-10 09:15:29.016 Illegal character in path at index 0: {{ outputs.convert.uri }}
2024-06-10 09:15:29.016 java.net.URISyntaxException: Illegal character in path at index 0: {{ outputs.convert.uri }}
	at java.base/java.net.URI$Parser.fail(Unknown Source)
	at java.base/java.net.URI$Parser.checkChars(Unknown Source)
	at java.base/java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.base/java.net.URI$Parser.parse(Unknown Source)
	at java.base/java.net.URI.<init>(Unknown Source)
	at io.kestra.plugin.serdes.excel.IonToExcel.writeQuery(IonToExcel.java:125)
	at io.kestra.plugin.serdes.excel.IonToExcel.run(IonToExcel.java:96)
	at io.kestra.plugin.serdes.excel.IonToExcel.run(IonToExcel.java:37)
	at io.kestra.core.runners.WorkerTaskThread.doRun(WorkerTaskThread.java:77)
	at io.kestra.core.runners.AbstractWorkerThread.run(AbstractWorkerThread.java:56)
```

### Steps To Reproduce

1. Use the flow as shown in the Example flow below
2. Execute it.

### Environment Information

- Kestra Version: 0.17.0
- Plugin version: 0.17.0
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):

### Example flow

```
id: ion_to_excel
namespace: dev

tasks:
  - id: http_download
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/products.csv

  - id: convert
    type: io.kestra.plugin.serdes.csv.CsvToIon
    from: "{{ outputs.http_download.uri }}"

  - id: to_excel
    type: io.kestra.plugin.serdes.excel.IonToExcel
    from: "{{ outputs.convert.uri }}"
```

**Comment by loicmathieu** [comment]
This has been fixed in https://github.com/kestra-io/plugin-serdes/pull/116 and released in 0.17.1.
